{% set version = "1.5.4" %}
# library version is different from project version
# Check 'meson.build' upstream in every release!
{% set so_name = "7.0.0" %}
{% set so_name_major = so_name.split('.')[0] %}

package:
  name: dav1d-split
  version: {{ version }}

source:
  url: https://code.videolan.org/videolan/dav1d/-/archive/{{ version }}/dav1d-{{ version }}.tar.gz
  sha256: a1d5b63d2d38ec9bd03acf643caa51fa22edd1e89c5a109c4807717216bbec07

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - meson >=0.49
    - ninja
    - nasm >=2.14
    - pkg-config
{% if target_platform == "win-arm64" %}
    - m2-perl
    - clang
{% endif %}

outputs:

  # Everything needed to build against libdav1d (excludes binary)
  - name: dav1d-dev
    files:
      include:
        - "include/**/*"  # [unix]
        - "lib/**/*"      # [unix]
        - "Library/include/**/*"  # [win]
        - "Library/lib/**/*"      # [win]
      exclude:
        # versioned libs
        - "lib/lib*.*.dylib"  # [osx]
        - "lib/lib*.so.*"  # [linux]
        # static libs
        - "lib/lib*.a"  # [unix]
        - "Library/lib/*.a.lib"  # [win]
        - "Library/lib/*_a.lib"  # [win]
        - "Library/lib/*static.lib"  # [win]
        - "lib/**/*static*"  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libdav1d' ~ so_name_major) }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      run:
        - {{ pin_subpackage('libdav1d' ~ so_name_major, exact=True) }}        # [unix]
    test:
      commands:
      # Need these things
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}                       # [unix]
        - test -f ${PREFIX}/lib/libdav1d.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\lib\\dav1d.lib exit 1               # [win]
        - test -f ${PREFIX}/include/dav1d/dav1d.h                             # [unix]
        - if not exist %PREFIX%\\Library\\include\\dav1d\\dav1d.h exit 1      # [win]
        - test -f ${PREFIX}/lib/pkgconfig/dav1d.pc                            # [unix]
        - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\dav1d.pc exit 1     # [win]
      # Exclude these things
        - test ! -f ${PREFIX}/lib/libdav1d.a                                  # [unix]
        - if exist %PREFIX%\\Library\\bin\\dav1d.dll exit 1                   # [win]
        - test ! -f ${PREFIX}/bin/dav1d                                       # [unix]
        - if exist %PREFIX%\\Library\\bin\\dav1d exit 1                       # [win]

  # Everything needed to run the dav1d binary
  - name: dav1d
    files:
      include:
        - "bin/**/*"  # [unix]
        - "doc/**/*"  # [unix]
        - "share/**/*"  # [unix]
        - "Library/bin/**/*"  # [win]
        - "Library/doc/**/*"  # [win]
        - "Library/share/**/*"  # [win]
      exclude:
        - "Library/bin/*.dll"  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      host:
        - {{ pin_subpackage('dav1d-dev', exact=True) }}
      run:
        - {{ pin_subpackage('libdav1d' ~ so_name_major) }}
    test:
      commands:
      # Need these things
        - dav1d -v
        - test -f ${PREFIX}/lib/libdav1d.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\bin\\dav1d.dll exit 1               # [win]
      # Exclude these things
        - test ! -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\dav1d.lib exit 1                   # [win]
        - test ! -f ${PREFIX}/include/dav1d/dav1d.h                           # [unix]
        - if exist %PREFIX%\\Library\\include\\dav1d\\dav1d.h exit 1          # [win]
        - test ! -f ${PREFIX}/lib/pkgconfig/dav1d.pc                          # [unix]
        - if exist %PREFIX%\\Library\\lib\\pkgconfig\\dav1d.pc exit 1         # [win]

  # Only what's needed for run_exports downstream
  - name: libdav1d{{ so_name_major }}
    files:
      include:
        - "Library/bin/*.dll"  # [win]
        - "lib/lib*.*.dylib"  # [osx]
        - "lib/lib*.so.*"  # [linux]
    build:
      run_exports:
        - {{ pin_subpackage('libdav1d' ~ so_name_major) }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      run:
        - {{ pin_subpackage('_libdav1d_api', max_pin='x.x.x') }}              # [win]
    test:
      commands:
      # Need these things
        - test -f ${PREFIX}/lib/libdav1d.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\bin\\dav1d.dll exit 1               # [win]
      # Exclude these things
        - test ! -f ${PREFIX}/lib/libdav1d.{{ so_name }}{{ SHLIB_EXT }}       # [osx]
        - test ! -f ${PREFIX}/bin/dav1d                                       # [unix]
        - if exist %PREFIX%\\Library\\bin\\dav1d exit 1                       # [win]
        - test ! -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\dav1d.lib exit 1                   # [win]
        - test ! -f ${PREFIX}/include/dav1d/dav1d.h                           # [unix]
        - if exist %PREFIX%\\Library\\include\\dav1d\\dav1d.h exit 1          # [win]
        - test ! -f ${PREFIX}/lib/pkgconfig/dav1d.pc                          # [unix]
        - if exist %PREFIX%\\Library\\lib\\pkgconfig\\dav1d.pc exit 1         # [win]

  # Clobber preventer for Windows; prevents multiple dav1d.dll files from being
  # installed simultaneously. This lets us avoid exporting a strict pin on the
  # libdav1d API which is not strictly correlated with the ABI.
  - name: _libdav1d_api
    build:
      skip: true  # [not win]
    about:
      summary: >
        An empty package that prevents multiple ABIs of libdavid being installed simultaneously on Windows.

about:
  home: https://code.videolan.org/videolan/dav1d
  summary: dav1d is the fastest AV1 decoder on all platforms
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING

extra:
  feedstock-name: dav1d
  recipe-maintainers:
    - carterbox
    - jaimergp
